image: ubuntu

stack: go 1.12

version: '{build}'

install:
- 'if [[ $APPVEYOR_REPO_TAG == "true" ]]; then appveyor UpdateBuild -Version "$(git describe --tags --always).$APPVEYOR_BUILD_ID"; else appveyor UpdateBuild -Version "$(git rev-parse --short HEAD).$APPVEYOR_BUILD_ID"; fi'
- sudo apt update
- sudo apt install -y jq
- go mod download

build: off

test_script:
- go test -v ./...
- 'go run jiup/rules/reachability-test/main.go || [[ $APPVEYOR_FORCED_BUILD == "True" ]] || [[ $APPVEYOR_RE_BUILD == "True" ]]'

for:
- branches:
    only:
    - master
  environment:
    GITHUB_TOKEN:
      secure: jnQXdVRI6HFMlf4o2lgVVlKyPO3jXsoxffGYNpcExEeMtSZUYQYPmXRGn9ykvZsl
  deploy_script:
  - git clone https://github.com/just-install/registry
  - bash deploy.sh
