language: go

go:
  - "1.12.x"

install:
  - git clone https://github.com/just-install/registry

script:
  - go test -v ./...
  - go run jiup/rules/reachability-test/main.go

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - bash deploy.sh
    on:
      branch: master